### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by RobJN** [mvexel/meetyourmappers#16]
I cannot access the website any more. Is it temporary or is this project now ended? https://mym.rtijn.org/

**Comment by darkhamaus** [comment]
The project seems to still be active but cannot be accessed everywhere. In the introduction [video](https://archive.org/details/osm-meet-your-mappers) by Martijn van Exel we see the date is 20200829

**Comment by mvexel** [comment]
Hey, yes, the site was down, I had some server trouble. It's up again though! Feel free to re-open if you find it doesn't work

**Comment by darkhamaus** [comment]
Sorry but it's still down for me
