### ISSUE TITLE
Allow choosing a server

### ISSUE THREAD

**Issue by Zverik** [mvexel/meetyourmappers#4]
First, thanks for the tool, I enjoyed browsing through mappers in my area. Very clever work with a mapper status :)

Alas, in Russia, the main overpass server is blocked by Roskomnadzor. We use alternative servers: namely, the kumi.systems one (see the list in overpass-turbo). Could you please add a checkbox "use alternative overpass server" that switches the servers?

I did the same in [osm_conflate](https://github.com/mapsme/osm_conflate/blob/master/conflate/osm.py), you can use the URL from the code.

**Comment by mvexel** [comment]
Yea, that sounds doable.. Do you want to add it? May be quicker :)

**Comment by mvexel** [comment]
work on this in the https://github.com/mvexel/meetyourmappers/tree/alt-server branch

**Comment by Zverik** [comment]
Great, thank you!

**Comment by mvexel** [comment]
Apologies, it wasn't 😊 
It will be in #10 however. To deploy shortly.
