### ISSUE TITLE
Support bounding box areas

### ISSUE THREAD

**Issue by maxerickson** [mvexel/meetyourmappers#5]
The first iteration of the UI could just be an input box for an Overpass-API style bbox string.

Could also have a map widget for drawing one.

This would be an escape hatch for people that get confused about the relation or can't find a suitable relation.

**Comment by mvexel** [comment]
That would be neat. My front end skills are minimal. A map widget would take an outsized amount of time for me to make, but I welcome a PR!

A bbox would be easier to do. perhaps paste an OSM map URL and derive bbox from that the way JOSM does?

**Comment by mvexel** [comment]
Work on this is now ongoing at https://github.com/mvexel/meetyourmappers/tree/bbox but for me to be able to test I need to resolve https://github.com/osmcode/pyosmium/issues/70 ...
